GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDczODA5NjAsImV4cCI6MTcwNzM4MTMyMCwiYXVkIjoiNjVjNDkwZTA5NzgxNjc0MGFjOGI3MWZkIiwiaXNzIjoibmV3c3BpbGwuYWkifQ.UZIAesNo63ax6jVAy65PYzyq2LnG-RSLm5fFTlQtwPU

### Login Route 
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "dsf78fdtruly123@gmail.com",
	"password": "1234"
}

### Register Route 
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
	"email": "dsf78fdtruly123@gmail.com",
	"password": "1234"
}

### Refresh token Route 
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDczODEwMTEsImV4cCI6MTczODkzODYxMSwiYXVkIjoiNjVjNDkwZTA5NzgxNjc0MGFjOGI3MWZkIiwiaXNzIjoibmV3c3BpbGwuYWkifQ.FSuEFZIpTM7r-GUxKo28RgO4wXRlDSfmVgz8DhcYn-s"

}


### Logout Route 
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
	"refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDczODE2OTUsImV4cCI6MTczODkzOTI5NSwiYXVkIjoiNjVjNDkzYmY5NzgxNjc0MGFjOGI3MjA0IiwiaXNzIjoibmV3c3BpbGwuYWkifQ.Ztu0jVQQ329BRDXhzOLRMh7mpgKVtWF1BWz34ESlrG8"
}

### News api
GET http://localhost:3000/news

